-- MySQL Script generated by MySQL Workbench
-- Пн 01 фев 2021 20:30:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`poll`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`poll` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `slug` VARCHAR(64) NULL,
        `question` VARCHAR(255) NULL,
        PRIMARY KEY (`id`),
        UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE
    )
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `test`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`answer` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `poll_id` INT NOT NULL,
        `answer` VARCHAR(255) NULL,
        PRIMARY KEY (`id`),
        INDEX `fk_answer_1_idx` (`poll_id` ASC) VISIBLE,
        CONSTRAINT `fk_answer_1`
           FOREIGN KEY (`poll_id`)
               REFERENCES `test`.`poll` (`id`)
               ON DELETE NO ACTION
               ON UPDATE NO ACTION
    )
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `test`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`result` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `poll_id` INT NOT NULL,
        `answer_id` INT NOT NULL,
        `name` VARCHAR(255) NOT NULL,
        PRIMARY KEY (`id`),
        INDEX `fk_result_1_idx` (`poll_id` ASC) VISIBLE,
        INDEX `fk_result_2_idx` (`answer_id` ASC) VISIBLE,
        CONSTRAINT `fk_result_1`
           FOREIGN KEY (`poll_id`)
               REFERENCES `test`.`poll` (`id`)
               ON DELETE NO ACTION
               ON UPDATE NO ACTION,
        CONSTRAINT `fk_result_2`
           FOREIGN KEY (`answer_id`)
               REFERENCES `test`.`answer` (`id`)
               ON DELETE NO ACTION
               ON UPDATE NO ACTION
    )
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
